## Importing the neccessary dependecies

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# print the dataset
df1 = pd.read_csv("/content/2025_data.csv", encoding='latin-1')
df1.head()

,Country,Indicator,Source,Unit,Currency,Frequency,Country Code,Time,Amount
0,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2007-01-01,-56213
1,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2008-01-01,-67563
2,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2009-01-01,-72379
3,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2010-01-01,-98886
4,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2011-01-01,-134138

In [ ]:
df1["Indicator"].unique()

array(['Budget Deficit/Surplus', 'Capital Expenditure',
       'Consumer Price Index (CPI)', 'Defence Expenditure',
       'Education Expenditure', 'Expenditure', 'Exports',
       'Food Inflation ', 'Food Inflation YoY', 'GDP Growth Rate',
       'GDP per Capita', 'GDP per capita', 'GDP per Capita ',
       'Government Debt', 'Health Expenditure', 'Imports',
       'Inflation Rate', 'Inflation Rate ', 'Interest Rate',
       'Labour Force', 'Nominal GDP', 'Population', 'Real GDP', 'Revenue',
       'Tax Revenue', 'Unemployment Rate', 'Value Added Tax (VAT)'],
      dtype=object)

In [ ]:
df1["Country"].unique()

array(['Egypt', 'Ethiopia', 'Ghana', 'Ivory Coast', 'Nigeria',
       'South Africa', 'Tanzania', 'Togo', 'Senegal', 'Kenya', 'Rwanda',
       'Algeria', 'Angola', 'Botswana'], dtype=object)

In [ ]:
df1["Source"].unique()

array(['Central Bank of Egypt', 'National Bank of Ethiopia',
       'Bank of Ghana', 'Central Bank of West African States',
       'Central Bank of Nigeria', 'South African Reserve Bank',
       'National Statistics Office, Tanzania',
       'Senegal Opendata for Africa', 'Central Bank of Kenya',
       'Ministry of Finance and Economic Planning, Rwanda',
       'Department of Statistics, South Africa.',
       'Senegal National statistical Site', 'Bank of Algeria',
       'National Bank of Angola', 'Ghana Statistical Service',
       'National Bureau of Statistics',
       'National Institute of Statistics of Rwanda',
       'Kenya National Bureau of Statistics', 'Bank of Tanzania',
       'Ministry of Planning and Economic Development, Egypt',
       'statistics Botswana', 'Debt Management Office, Nigeria',
       'National Bank of Rwanda', 'Bank of Botswana',
       'Department of Statistics, South Africa',
       'National Statistics Office, Algeria',
       'Central Agency for Public Mobilization and Statistics',
       'South African Revenue Service'], dtype=object)

In [ ]:
df2 = df1.drop_duplicates(subset=["Country","Indicator", "Time"]).copy()

In [ ]:
df2["Indicator"].unique()

array(['Budget Deficit/Surplus', 'Capital Expenditure',
       'Consumer Price Index (CPI)', 'Defence Expenditure',
       'Education Expenditure', 'Expenditure', 'Exports',
       'Food Inflation ', 'Food Inflation YoY', 'GDP Growth Rate',
       'GDP per Capita', 'GDP per capita', 'GDP per Capita ',
       'Government Debt', 'Health Expenditure', 'Imports',
       'Inflation Rate', 'Inflation Rate ', 'Interest Rate',
       'Labour Force', 'Nominal GDP', 'Population', 'Real GDP', 'Revenue',
       'Tax Revenue', 'Unemployment Rate', 'Value Added Tax (VAT)'],
      dtype=object)

In [ ]:
print(len(df1["Time"]))

print(len(df2["Time"]))

23784
22615

In [ ]:
df2.head()

,Country,Indicator,Source,Unit,Currency,Frequency,Country Code,Time,Amount
0,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2007-01-01,-56213
1,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2008-01-01,-67563
2,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2009-01-01,-72379
3,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2010-01-01,-98886
4,Egypt,Budget Deficit/Surplus,Central Bank of Egypt,Million,EGP,Yearly,EGY,2011-01-01,-134138

In [ ]:
print(len(df2["Source"]))
print(len(df2["Country Code"]))

22615
22615

In [ ]:
print(df2["Country"].unique())
len(df2["Country"].unique())

['Egypt' 'Ethiopia' 'Ghana' 'Ivory Coast' 'Nigeria' 'South Africa'
 'Tanzania' 'Togo' 'Senegal' 'Kenya' 'Rwanda' 'Algeria' 'Angola'
 'Botswana']

14

In [ ]:
print(df2["Country Code"].unique())
len(df2["Country Code"].unique())

['EGY' 'ETH' 'GHA' 'CIV' 'NGA' 'ZAF' 'TZA' 'TGO' 'SEN' 'KEN' 'RWA' 'DZA'
 'AGO' 'BWA']

14

In [ ]:
df2.Indicator.unique()

array(['Budget Deficit/Surplus', 'Capital Expenditure',
       'Consumer Price Index (CPI)', 'Defence Expenditure',
       'Education Expenditure', 'Expenditure', 'Exports',
       'Food Inflation ', 'Food Inflation YoY', 'GDP Growth Rate',
       'GDP per Capita', 'GDP per capita', 'GDP per Capita ',
       'Government Debt', 'Health Expenditure', 'Imports',
       'Inflation Rate', 'Inflation Rate ', 'Interest Rate',
       'Labour Force', 'Nominal GDP', 'Population', 'Real GDP', 'Revenue',
       'Tax Revenue', 'Unemployment Rate', 'Value Added Tax (VAT)'],
      dtype=object)

In [ ]:
df2["Indicator"] = df2["Indicator"].replace("Budget Deficit/Surplus", "Budget Deficit")

In [ ]:
df2.head()

,Country,Indicator,Source,Unit,Currency,Frequency,Country Code,Time,Amount
0,Egypt,Budget Deficit,Central Bank of Egypt,Million,EGP,Yearly,EGY,2007-01-01,-56213
1,Egypt,Budget Deficit,Central Bank of Egypt,Million,EGP,Yearly,EGY,2008-01-01,-67563
2,Egypt,Budget Deficit,Central Bank of Egypt,Million,EGP,Yearly,EGY,2009-01-01,-72379
3,Egypt,Budget Deficit,Central Bank of Egypt,Million,EGP,Yearly,EGY,2010-01-01,-98886
4,Egypt,Budget Deficit,Central Bank of Egypt,Million,EGP,Yearly,EGY,2011-01-01,-134138

In [ ]:
df2["Amount"].isnull().sum()

np.int64(59)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22615 entries, 0 to 23783
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       22615 non-null  object
 1   Indicator     22615 non-null  object
 2   Source        22615 non-null  object
 3   Unit          22593 non-null  object
 4   Currency      12317 non-null  object
 5   Frequency     22615 non-null  object
 6   Country Code  22615 non-null  object
 7   Time          22614 non-null  object
 8   Amount        22556 non-null  object
dtypes: object(9)
memory usage: 2.2+ MB

In [ ]:
df2.drop("Currency", axis=1, inplace=True)

In [ ]:
df4 = df2.dropna().copy()

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22533 entries, 0 to 23783
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       22533 non-null  object
 1   Indicator     22533 non-null  object
 2   Source        22533 non-null  object
 3   Unit          22533 non-null  object
 4   Frequency     22533 non-null  object
 5   Country Code  22533 non-null  object
 6   Time          22533 non-null  object
 7   Amount        22533 non-null  object
dtypes: object(8)
memory usage: 1.5+ MB

In [ ]:
df4.Amount.unique()

array(['-56213', '-67563', '-72379', ..., '5218', '6298', '7067'],
      dtype=object)

In [ ]:
# remove the negative sign and commas in the amount column
df4["Amount"]= df4["Amount"].astype(str).str.replace("-", "").str.replace(",", "")

In [ ]:
df5 = df4.copy()

In [ ]:
df5["Amount"].unique()

array(['-56213', '-67563', '-72379', ..., '5218', '6298', '7067'],
      dtype=object)

In [ ]:
df5.head()

,Country,Indicator,Source,Unit,Frequency,Country Code,Time,Amount
0,Egypt,Budget Deficit,Central Bank of Egypt,Million,Yearly,EGY,2007-01-01,-56213
1,Egypt,Budget Deficit,Central Bank of Egypt,Million,Yearly,EGY,2008-01-01,-67563
2,Egypt,Budget Deficit,Central Bank of Egypt,Million,Yearly,EGY,2009-01-01,-72379
3,Egypt,Budget Deficit,Central Bank of Egypt,Million,Yearly,EGY,2010-01-01,-98886
4,Egypt,Budget Deficit,Central Bank of Egypt,Million,Yearly,EGY,2011-01-01,-134138

In [ ]:
df5.Amount.unique()

array(['-56213', '-67563', '-72379', ..., '5218', '6298', '7067'],
      dtype=object)

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22533 entries, 0 to 23783
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       22533 non-null  object
 1   Indicator     22533 non-null  object
 2   Source        22533 non-null  object
 3   Unit          22533 non-null  object
 4   Frequency     22533 non-null  object
 5   Country Code  22533 non-null  object
 6   Time          22533 non-null  object
 7   Amount        22533 non-null  object
dtypes: object(8)
memory usage: 2.1+ MB

## Create a Function that converts Amount column to Apporpriate Value

In [ ]:
def convert_to_usd(df):
    """
    Converts monetary indicators to USD million while preserving
    non-monetary indicators in their original units.

    Handles mixed million/billion monetary units.

    Required columns:
    Country, Indicator, Amount, Unit
    """

    exchange_rates = {
        "Egypt": 49.38,
        "Ethiopia": 217.30,
        "Ghana": 11.29,
        "Ivory Coast": 578.00,
        "Nigeria": 1380.43,
        "South Africa": 22.26,
        "Tanzania": 3571.00,
        "Togo": 578.00,
        "Senegal": 578.00,
        "Kenya": 129.60,
        "Rwanda": 2000.00,
        "Algeria": 133.23,
        "Angola": 1250.00,
        "Botswana": 13.40
    }

    df = df.copy()

    # Clean text columns
    df["Indicator"] = df["Indicator"].astype(str).str.strip()
    df["Unit"] = df["Unit"].astype(str).str.strip()
    df["Country"] = df["Country"].astype(str).str.strip()


    # Indicators measured as monetary values
    monetary = {
        "Budget Deficit",
        "Capital Expenditure",
        "Defence Expenditure",
        "Education Expenditure",
        "Expenditure",
        "Exports",
        "GDP per Capita",
        "Government Debt",
        "Health Expenditure",
        "Imports",
        "Nominal GDP",
        "Real GDP",
        "Revenue",
        "Tax Revenue",
        "Value Added Tax (VAT)"
    }


    percentage = {
        "Inflation Rate",
        "Food Inflation",
        "Food Inflation YoY",
        "GDP Growth Rate",
        "Interest Rate",
        "Unemployment Rate"
    }


    index = {
        "Consumer Price Index (CPI)"
    }


    count = {
        "Population",
        "Labour Force"
    }


    # Start with original amount
    df["Value"] = df["Amount"]


    # Monetary rows
    monetary_mask = df["Indicator"].isin(monetary)


    # Convert billions into millions
    billion_mask = (
        monetary_mask &
        df["Unit"].str.contains(
            r"Billion|Billions|bn|B",
            case=False,
            na=False
        )
    )


    df.loc[billion_mask, "Value"] = (
        df.loc[billion_mask, "Value"] * 1000
    )


    # Convert local currency to USD
    df.loc[monetary_mask, "Value"] = (
        df.loc[monetary_mask, "Value"] /
        df.loc[monetary_mask, "Country"].map(exchange_rates)
    )


    # Final unit labels
    df.loc[monetary_mask, "Unit"] = "USD million"

    df.loc[df["Indicator"].isin(percentage), "Unit"] = "%"

    df.loc[df["Indicator"].isin(index), "Unit"] = "Index"

    df.loc[df["Indicator"].isin(count), "Unit"] = "Persons"


    return df

In [ ]:
# convert the amount column to numeric
df5["Amount"] = pd.to_numeric(df5["Amount"], errors='coerce')
converted_df = convert_to_usd(df5)

In [ ]:
convert_to_usd(df5)

,Country,Indicator,Source,Unit,Frequency,Country Code,Time,Amount,Value
0,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2007-01-01,-56213.0,-1138.375861
1,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2008-01-01,-67563.0,-1368.226002
2,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2009-01-01,-72379.0,-1465.755367
3,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2010-01-01,-98886.0,-2002.551640
4,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2011-01-01,-134138.0,-2716.443904
...,...,...,...,...,...,...,...,...,...
23779,Tanzania,Value Added Tax (VAT),"National Statistics Office, Tanzania",USD million,Yearly,TZA,2019-01-01,4781.6,1339.008681
23780,Tanzania,Value Added Tax (VAT),"National Statistics Office, Tanzania",USD million,Yearly,TZA,2020-01-01,5184.0,1451.694203
23781,Tanzania,Value Added Tax (VAT),"National Statistics Office, Tanzania",USD million,Yearly,TZA,2021-01-01,5218.0,1461.215346
23782,Tanzania,Value Added Tax (VAT),"National Statistics Office, Tanzania",USD million,Yearly,TZA,2022-01-01,6298.0,1763.651638
23783,Tanzania,Value Added Tax (VAT),"National Statistics Office, Tanzania",USD million,Yearly,TZA,2023-01-01,7067.0,1978.997480

In [ ]:
df6 = convert_to_usd(df5).copy()

In [ ]:
df6.loc[df6["Indicator"] == "GDP per capita"]

,Country,Indicator,Source,Unit,Frequency,Country Code,Time,Amount,Value
9744,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2015-01-01,NaN,NaN
9745,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2016-01-01,NaN,NaN
9746,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2017-01-01,NaN,NaN
9747,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2018-01-01,NaN,NaN
9748,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2019-01-01,NaN,NaN
9749,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2020-01-01,NaN,NaN
9750,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2021-01-01,NaN,NaN
9751,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2022-01-01,NaN,NaN
9752,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2023-01-01,NaN,NaN
9753,Botswana,GDP per capita,statistics Botswana,Million,Yearly,BWA,2024-01-01,NaN,NaN

In [ ]:
print(df6["Indicator"].unique())

['Budget Deficit' 'Capital Expenditure' 'Consumer Price Index (CPI)'
 'Defence Expenditure' 'Education Expenditure' 'Expenditure' 'Exports'
 'Food Inflation' 'Food Inflation YoY' 'GDP Growth Rate' 'GDP per capita'
 'GDP per Capita' 'Government Debt' 'Health Expenditure' 'Imports'
 'Inflation Rate' 'Interest Rate' 'Labour Force' 'Nominal GDP'
 'Population' 'Real GDP' 'Revenue' 'Tax Revenue' 'Unemployment Rate'
 'Value Added Tax (VAT)']

In [ ]:
df6.loc[df6["Indicator"].str.contains("GDP per", case=False), "Indicator"].value_counts(dropna=False)

Indicator
GDP per Capita    49
GDP per capita    10
Name: count, dtype: int64

In [ ]:
df6["Indicator"] = (
    df6["Indicator"]
        .str.strip()
        .replace({
            "GDP per capita": "GDP per Capita",
            "GDP per Capita": "GDP per Capita",
            "Inflation Rate": "Inflation Rate",
            "Inflation Rate ": "Inflation Rate",
            "Food Inflation": "Food Inflation",
            "Food Inflation ": "Food Inflation"
        })
)

In [ ]:
df6.head()

,Country,Indicator,Source,Unit,Frequency,Country Code,Time,Amount,Value
0,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2007-01-01,-56213.0,-1138.375861
1,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2008-01-01,-67563.0,-1368.226002
2,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2009-01-01,-72379.0,-1465.755367
3,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2010-01-01,-98886.0,-2002.551640
4,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2011-01-01,-134138.0,-2716.443904

In [ ]:
df6.Indicator.unique()

array(['Budget Deficit', 'Capital Expenditure',
       'Consumer Price Index (CPI)', 'Defence Expenditure',
       'Education Expenditure', 'Expenditure', 'Exports',
       'Food Inflation', 'Food Inflation YoY', 'GDP Growth Rate',
       'GDP per Capita', 'Government Debt', 'Health Expenditure',
       'Imports', 'Inflation Rate', 'Interest Rate', 'Labour Force',
       'Nominal GDP', 'Population', 'Real GDP', 'Revenue', 'Tax Revenue',
       'Unemployment Rate', 'Value Added Tax (VAT)'], dtype=object)

In [ ]:
df6.loc[df6["Indicator"] == "Government Debt", "Value"]

9803      384.052248
9804      369.198056
9805      382.027136
9806      394.734710
9807      438.256379
            ...
10919    1697.750865
10920    1840.830450
10921    5773.875433
10922    6415.051903
10923    7191.349481
Name: Value, Length: 1101, dtype: float64

In [ ]:
df6.head()

,Country,Indicator,Source,Unit,Frequency,Country Code,Time,Amount,Value
0,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2007-01-01,-56213.0,-1138.375861
1,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2008-01-01,-67563.0,-1368.226002
2,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2009-01-01,-72379.0,-1465.755367
3,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2010-01-01,-98886.0,-2002.551640
4,Egypt,Budget Deficit,Central Bank of Egypt,USD million,Yearly,EGY,2011-01-01,-134138.0,-2716.443904

In [ ]:
df6["Indicator"].unique()

array(['Budget Deficit', 'Capital Expenditure',
       'Consumer Price Index (CPI)', 'Defence Expenditure',
       'Education Expenditure', 'Expenditure', 'Exports',
       'Food Inflation', 'Food Inflation YoY', 'GDP Growth Rate',
       'GDP per Capita', 'Government Debt', 'Health Expenditure',
       'Imports', 'Inflation Rate', 'Interest Rate', 'Labour Force',
       'Nominal GDP', 'Population', 'Real GDP', 'Revenue', 'Tax Revenue',
       'Unemployment Rate', 'Value Added Tax (VAT)'], dtype=object)

In [ ]:
# remove the negative sign and commas in the amount column
df6["Amount"]= df6["Amount"].astype(str).str.replace("-", "").str.replace(",", "")
df6["Value"]= df6["Value"].astype(str).str.replace("-", "").str.replace(",", "")

In [ ]:
df6.to_csv("economic_data_clean.csv", index=False)

In [ ]:
df6.columns

Index(['Country', 'Indicator', 'Source', 'Unit', 'Frequency', 'Country Code',
       'Time', 'Amount', 'Value'],
      dtype='object')

In [ ]:
df6.drop(["Country Code", "Amount", "Source"], axis=1, inplace=True)

KeyError: "['Country Code', 'Amount', 'Source'] not found in axis"

In [ ]:
df6.drop("Frequency", axis=1, inplace=True)

In [ ]:
df6.columns

Index(['Country', 'Indicator', 'Unit', 'Time', 'Value'], dtype='object')

In [ ]:
df6.to_csv("economic_data_clean.csv", index=False)